# Generated by Django 4.1.7 on 2023-03-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='function',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='name_permissions',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='rol',
            field=models.ManyToManyField(null=True, to='person.rol'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='name_rol',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='user',
            field=models.ManyToManyField(null=True, to='person.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
